### ISSUE TITLE
Option for unscaled output

### ISSUE THREAD

**Issue by msikma** [libretro/QuickNES_Core#11]
First of all, I'm not sure if this is the correct place to ask for this. If this should be raised on the RetroArch repo, I apologize.

I've been using QuickNES on the 3DS, and it works fantastic. I was wondering if it was possible to include an option to not scale the emulator output, and simply keep it 1:1. Currently, it uses bilinear scale, which softens the output a bit. Here's an example.

![img_4117](https://cloud.githubusercontent.com/assets/1507745/24198946/34e8fa4c-0f08-11e7-94c5-73d23da7b35b.JPG)

Since there's only 16 pixels difference between screen edge cropped NES and the 3DS's screen height, it would be nice to have the option to simply display the output letterboxed.

**Comment by hizzlekizzle** [comment]
I think enabling integer scaling in settings > video should do it.

**Comment by msikma** [comment]
In the build that I've got, there are no settings at all. Maybe this is a unique feature of the 3DS build of RetroArch, but there's no option to change the video output anywhere to be found. The "core options" menu displays a message saying that there are no core options.

The NEStopia build did have some different core options, like NTSC video filtering, so I assumed they would have to be part of the core, but maybe this is a missing feature of RetroArch itself?

**Comment by hizzlekizzle** [comment]
From the menu where you see the core options, try pressing 'b' a couple of times to get up to the main menu, from there you should be able to go to settings  > video.

**Comment by msikma** [comment]
I assume you mean the main menu? I just tried to see if I could get anywhere else but unfortunately it's just not there. That's on the [1.4.1 build](https://buildbot.libretro.com/stable/1.4.1/nintendo/3ds/). I guess it should be there, though? Do you think I should raise this on the RetroArch repo?

**Comment by msikma** [comment]
Just for reference, here's all I can see in my main menu.

![img_1054](https://cloud.githubusercontent.com/assets/1507745/24210964/f8493372-0f2a-11e7-957b-8e6884233db7.JPG)
![img_5554](https://cloud.githubusercontent.com/assets/1507745/24210963/f847e972-0f2a-11e7-875e-8efb2015aa59.JPG)

**Comment by bparker06** [comment]
Try to press left/right to switch between tabs of the menu, Main Menu is the far left tab and Settings is just to the right if that. If Settings -> Video there is a Bilinear Filter option, turning that off will switch it ti Nearest Neighbor and get rid if the blurriness. You might have to enable Settings -> User Interface -> Show Advanced Options to see everything.

**Comment by msikma** [comment]
There it is! Oh wow, thanks for helping me and sorry for wasting your time. I really had absolutely no idea that there were other menus to the left and right... there wasn't really any indication.

You're right, the video settings are there, and so are the options for setting the scaling method.
