### ISSUE TITLE
[Feature request] Turbo buttons

### ISSUE THREAD

**Issue by Ledarium** [libretro/QuickNES_Core#15]
Turbo buttons does not work or at least I had not figured out how to enable them. I am on commit 8613b48.

**Comment by retro-wertz** [comment]
core itself does not have turbo modes like the other NES cores. you can however use retroarch's own turbo toggle option by going into Input > Input User # Binds > and assigning a hotkey to User # Turbo Enable.

**Comment by hizzlekizzle** [comment]
I'm gonna go ahead and close this. Feel free to reopen if needed.
