### ISSUE TITLE
Bugs in "libretro.cpp": Wrong image size given to QuickNES causes graphical corruption

### ISSUE THREAD

**Issue by Dwedit** [libretro/QuickNES_Core#19]
In the function "retro_load_game", it is giving a 256 x 256 size image to QuickNES.
This is actually wrong, it turns out QuickNES actually wants a 272 pixel wide image, not a 256 pixel wide image, otherwise it overwrites the first and last 8 pixels on each scanline with junk data.

To fix this, I made these code changes to "libretro.cpp":

I defined these constants at the top right before retro_init:
```
const int videoBufferWidth = Nes_Emu::image_width + 16;
const int videoBufferHeight = Nes_Emu::image_height + 16;
```

Then changed the code for "retro_load_game" from this:
```
   static uint8_t video_buffer[Nes_Emu::image_width * (Nes_Emu::image_height + 16)];
   emu->set_pixels(video_buffer + (8 * Nes_Emu::image_width), Nes_Emu::image_width);
```
to this:
```
   static uint8_t video_buffer[videoBufferWidth * videoBufferHeight];
   emu->set_pixels(video_buffer + (8 * videoBufferWidth), videoBufferWidth);
```

Then in the function "retro_run", I changed this code:
```
   for (unsigned i = 0; i < Nes_Emu::image_width * Nes_Emu::image_height; i++)
      *out_pixels++ = retro_palette[in_pixels[i]];
```
to this:
```
   for (int y = 0; y < Nes_Emu::image_height; y++)
   {
	   uint16_t *out_scanline = video_buffer + Nes_Emu::image_width * y;
	   uint8_t *in_scanline = frame.pixels + videoBufferWidth * y;
	   for (int x = 0; x < Nes_Emu::image_width; x++)
	   {
		   out_scanline[x] = retro_palette[in_scanline[x]];
	   }
   }
```

After doing this, everything should be all fixed.
Note that if you have Overscan display hidden (which is the default setting in RetroArch), you never see this issue in the first place.

**Comment by Dwedit** [comment]
Also, it turns out you only need one extra row of pixels, not 16, and do not need to put the offset 8 rows into the image.

so then we get this:
```
const int videoBufferWidth = Nes_Emu::image_width + 16;
const int videoBufferHeight = Nes_Emu::image_height + 1;
```

and this:
```
   static uint8_t video_buffer[videoBufferWidth * videoBufferHeight];
   emu->set_pixels(video_buffer, videoBufferWidth);
```

**Comment by retro-wertz** [comment]
question... does quicknes even show the overscan portion of nes?

**Comment by Dwedit** [comment]
QuickNES absolutely shows the whole 256x240 image, just not in its currently shipped bugged state.

**Comment by retro-wertz** [comment]
ok great. quick-test this does show full 256px width. time to move overscan setting as a core option....

**Comment by retro-wertz** [comment]
according to Nes_emu::buffer_width and Nes_emu::buffer_height, buffers are 272x242
in standalone quicknes(windows), they initialize the buffer as buf_width * (buf_height +1)
e.g
```
   pixels = new unsigned char [(m_emu.buffer_height() + 1) * m_emu.buffer_width];
      if ( pixels )
         m_emu.set_pixels( pixels, m_emu.buffer_width );
```

**Comment by retro-wertz** [comment]
any update on this? are you going to push this and able to update the PSP section too?

**Comment by Dwedit** [comment]
I just redid the pull request, this time including the screen buffer fix, savestate fix, and not including the MSVC project files.
