### ISSUE TITLE
Crashes on Android

### ISSUE THREAD

**Issue by fr500** [libretro/QuickNES_Core#6]
Ref:
https://github.com/libretro/RetroArch/issues/3973#issuecomment-260448916

**Comment by fr500** [comment]
Pushed a change to allow it to build with DEBUG symbols, hopefully it will be enough to get a stacktrace.

**Comment by meleu** [comment]
Sorry my ignorance, but how can I get a stacktrace when RetroArch crashes on my Android?
Do you know any doc about it?

**Comment by fr500** [comment]
I'm just hoping with the debug symbols in place there will be enough info in the logcat.
Haven't had a chance to test yet

**Comment by meleu** [comment]
Sorry for the bumping, but this issue still happens.

**Comment by retro-wertz** [comment]
hi. this still happens in android. even without achievement enabled. This is probably something to do with nes' wram which metroid uses.

**Comment by retro-wertz** [comment]
This should be working now in latest commit....

**Comment by meleu** [comment]
will test it ASAP. thanks ;)

**Comment by retro-wertz** [comment]
can this be closed now? @meleu  @fr500 :+1: D

**Comment by hizzlekizzle** [comment]
Going to close this. Reopen if needed.
