### ISSUE TITLE
QuickNES unable to launch Contra (Japan)

### ISSUE THREAD

**Issue by meleu** [libretro/QuickNES_Core#7]
When trying to launch `Contra (Japan).nes` with QuickNES RetroArch log says:
```txt
RetroArch [ERROR] :: Failed to load content.
```

The same ROM runs just fine with FCEUmm.

This issue was detected when running tests for [this RetroArch issue](https://github.com/libretro/RetroArch/issues/4071).

**Comment by lasers** [comment]
Confirmed.

**Comment by retro-wertz** [comment]
Mapper 23 is not supported....

**Comment by meleu** [comment]
@retro-wertz what does it mean?

**Comment by retro-wertz** [comment]
well, mapper 23 which contra(japan) uses is not implemented in this core. someone has to add that somehow. quicknes only has limited supported mappers.

**Comment by LodanZark** [comment]
@meleu  Basically mappers are special chips that are found in the game PCB that translate graphics, programs and ram into cpu or ppu address spaces. You can find more informations about it here: https://wiki.nesdev.com/w/index.php/Mapper

**Comment by retro-wertz** [comment]
i've added mapper 23 and other mappers into the core. this should at least help those system that relies using this core.
