### ISSUE TITLE
[3DS] Crash when loading several games in a row

### ISSUE THREAD

**Issue by justinweiss** [libretro/QuickNES_Core#75]
If you load several roms (usually 2 or 3) without exiting the core, you'll get an ARM11 exception. Breaking into it with gdb, this is the stack:

```
(gdb) bt
#0  0x0028a258 in consolePrintChar (c=91)
    at /home/fincs/releases/ctrulib/libctru/source/console.c:704
#1  0x0028a844 in con_write (r=<optimized out>, fd=<optimized out>, ptr=<optimized out>,
    len=6) at /home/fincs/releases/ctrulib/libctru/source/console.c:476
#2  0x002c46bc in __sfvwrite_r ()
```

It looks like somehow libctru's `currentConsole` gets set to `0x57`, which means accessing any property of it will cause a crash.

**Comment by msikma** [comment]
I want to add that I have this same problem, on old 3DS. I can provide more details if needed.
