### ISSUE TITLE
WTF? Why the code was nuked and branch force pushed?

### ISSUE THREAD

**Issue by asavah** [libretro/QuickNES_Core#78]
See title.

**Comment by asavah** [comment]
For those that have git cloned locally:
```
git reflog
daf240e (HEAD, origin/master, origin/HEAD) HEAD@{0}: checkout: moving from d831377bfb2b08f44de40e55059c50a42124b724 to daf240eecb37aaa15e2ad4c499bb9fb39132ddc9
d831377 HEAD@{1}: checkout: moving from 31654810b9ebf8b07f9c4dc27197af7714364ea7 to d831377bfb2b08f44de40e55059c50a42124b724
3165481 (master) HEAD@{2}: checkout: moving from master to 31654810b9ebf8b07f9c4dc27197af7714364ea7
3165481 (master) HEAD@{3}: clone: from https://github.com/libretro/QuickNES_Core.git

git reset --hard d831377
HEAD is now at d831377 Merge pull request #77 from fjtrujy/ps2-newlib
```
This allows to checkout the repo at the point just before the force push.

@twinaphex I'm sorry to shamelessly ping you, but maybe it's possible this repo was compromised.

**Comment by twinaphex** [comment]
Yes, we are still waiting on Github to help us restore this repo if possible.

For more details on what happened yesterday, read this -

https://www.libretro.com/index.php/hacker-vandalised-our-buildbot-and-github-organization/

**Comment by asavah** [comment]
I see everything seems to be restored now.
It's really sad to see morons trying to harm this wonderful project .
